server:
  port: 8090

ca:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

redis:
  host: localhost
  port: 6379
  password: